# Generated by Django 4.2 on 2023-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
